### ISSUE TITLE
Consider using monotonic time

### ISSUE THREAD

**Issue by MSch** [navinpeiris/logster#1]
Thanks so much for taking the time and building this! You made my log-tailing day :)

Would you consider switching from `:os.timestamp` to `:erlang.monotonic_time`? See https://github.com/elixir-lang/plug/pull/373 for the equivalent change in Plug.

**Comment by navinpeiris** [comment]
You're welcome! :smile: 

Thanks for letting me know about the change to monotonic_time, version 0.1.3 has been released which uses that. I've removed support for `:os.timestamp` considering that the project requires elixir 1.2

**Comment by MSch** [comment]
Thank you!
