### ISSUE TITLE
JSON Formatter

### ISSUE THREAD

**Issue by mootpointer** [navinpeiris/logster#3]
I'm looking at logging to a service like Loggly, which does best with a JSON formatted log.

I love the work you've done, and wonder if you'd be open to a PR allowing different formatters.

I'm thinking it would be best to accumulate the data in a KW list, then format that KW list, either as JSON or as a set of `key=val` pairs.

Of course, if you don't want a JSON library as a dep of this library (which I totally understand), the PR would just allow for another package to come along and format the log line.

**Comment by navinpeiris** [comment]
Would love it!

We do currently include `poison` as a dependency so that we can print out the params nicely, which on hindsight probably shouldn't have been included, but considering how beneficial having a JSON formatter is to this project, not sure if it's that much of an issue

**Comment by mootpointer** [comment]
Okay, I've opened #4 and am using it in production.
